#!/bin/bash

if [ $# -eq 0 ]
then
	input+=`/bin/cat`
else
	input+=`echo $*`
fi

for path in "${input[@]}"
do
modules+="`/bin/find /"$path" -type f \( -iname "*.cil" \) | /bin/cut -d/ -f2-`"
done

for entry in ${modules[@]}
do
	test -f "$entry" || exit 1
	test -r "$entry" || exit 1
	test -s "$entry" || exit 1
done

if [ -z "$modules" ]
then
	exit 192
elif [ -n "$modules" ]
then
	echo "${modules[@]}"
else
	exit 1
fi

exit

#EOF
