#!/bin/bash

if [ $# -eq 1 ]
then
	input+=`echo $1`
else
	exit 1
fi

test -f "$input" || exit 1
test -r "$input" || exit 1
test -s "$input" || exit 1

homedirtemplate+="`/bin/grep 'HOME_DIR' "$input"`"

if [ -z "$homedirtemplate" ]
then
	exit 192
elif [ -n "$homedirtemplate" ]
then
	echo "${homedirtemplate[@]}"
else
	exit 1
fi

exit

#EOF
