#!/bin/bash

if [ -x /bin/git ]
then
	git fetch --recurse-submodules https://github.com/defensec/dssp \
		&& git pull --recurse-submodules https://github.com/defensec/dssp \
		&& git submodule update --recursive
fi

exit

#EOF
